[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.0"

[features]
seeds = true
skip-lint = false

[programs.localnet]
blackbook_bridge = "BBRDGEXXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[programs.devnet]
blackbook_bridge = "BBRDGEXXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[programs.mainnet]
blackbook_bridge = "TBD_AFTER_DEPLOY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet   = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/blackbook_bridge"]
